### ISSUE TITLE
How do I get it work?

### ISSUE THREAD

**Issue by limbo-lab** [mukyasa/MMCamScanner#1]
Compile fails.

**Comment by mukyasa** [comment]
add open CV and Tesseract SDK  for iOS,just google it, u will find link for SDK,Also in description i have added the link

**Comment by edvenkat** [comment]
Please advice how to download and install TesseractOCR and OpenCV....please give step by step
I try but getting error #import <TesseractOCR/TesseractOCR.h> and #include <opencv2/imgproc/imgproc.hpp> file not found
