### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by Ankish** [mukyasa/MMCamScanner#2]
I have added both frameworks. There might be lot of changes in new iOS versions. Can you look into the step of installation and make it easy for us to integrate your awesome lib ? :).  Have spent lot of time , but cant get it to working. Thanks!

**Comment by mukyasa** [comment]
Hey Ankish

its working on iOS9 also ,i have tested it.Just add both frameworks

OpenCv and Tesseract.

Download link bith framework are given on git

Thanks

**Comment by silviu-geronimo** [comment]
Hello,

How did I manage to get it working:
- downloaded MMCamScanner, opencv2.framework and Tesseract-ORC-iOS-master.
- Imported the opencv2.framework in MMCamScanner project.
- Runned 'pod install' in Tesseract-ORC-iOS-master root directory. (I think this is not mandatory)
- Runned 'pod install' in Tesseract-ORC-iOS-master/TesseractOCR folder
- Imported only Tesseract-ORC-iOS-master/TesseractOCR folder in MMCamScanner project
- Then the project will have a few errors: 

1) Change //#import <TesseractOCR/TesseractOCR.h> with #import "TesseractOCR.h"

2) Change "G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] init"]; with
"G8RecognitionOperation *operation = [[G8RecognitionOperation alloc] initWithLanguage:@"eng"];"

3) Remove the TesseractOCR.framwork from Project Build Phases - Link Binary with Libraries

It is not the best fix but it works.

Hope this will help you, good luck!

**Comment by edvenkat** [comment]
Please advice how to download and install TesseractOCR and OpenCV....please give step by step
I try but getting error #import <TesseractOCR/TesseractOCR.h> and #include <opencv2/imgproc/imgproc.hpp> file not found
