### ISSUE TITLE
'opencv2/imgproc/imgproc.hpp' file not found

### ISSUE THREAD

**Issue by alkanyunus** [mukyasa/MMCamScanner#4]
Even I added frameworks still cannot be compiled. Your documentation definitely is not enough to run your example. Are you sure it's working?

**Comment by mukyasa** [comment]
Hello saxahan, The project is absolutely working fine in latest SDK , I have mentioned the steps , Its very simple u have to download OpenCV SDK and drag and drop it,

Apart from OpenCV framework u also have to add Tesseract Framework, I have added the link of both SDK, Tesseract one is project u have to build it and drag drop the SDK

If u finding any difficulty in adding Tesseract framework comment the code of Tesseract . The project is running smoothly .

Below is hint to comment the Tesseract code, I have shared the file

[ViewController.m.zip](https://github.com/mukyasa/MMCamScanner/files/288234/ViewController.m.zip)

**Comment by edvenkat** [comment]
Please advice how to download and install TesseractOCR and OpenCV....please give step by step
I try but getting error #import <TesseractOCR/TesseractOCR.h> and #include <opencv2/imgproc/imgproc.hpp> file not found

**Comment by alkanyunus** [comment]
I've run the project after I opened this issue. Basically, try to follow your errors. And make sure TesseractOCR and OpenCV frameworks added correctly. Yes, I still agree that documentation is not good to understand for proceeding.

**Comment by mukyasa** [comment]
I understand your concerrn, but i cant add the OpenCV and Tesseract SDK as it size is big. Also the project is smooth to run , just drag and drop the downloaded SDK , no comment no headers issues. Am still sorry tat u faced this issue will try to make documentation more crystal clear also more Feedbacks are welcome.Thanks Cheers
